# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 didn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

after-startup-command = [
    'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color="grow(0xc0ffb3ba)" inactive_color=0x20494d64 width=5.0'
]

default-root-container-layout = 'tiles'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.right =      5
outer.top =        5

[mode.main.binding]
cmd-h = []
