import = [
    "~/.config/alacritty/themes/carbonfox.toml",
    "~/.config/alacritty/font.toml"
]

[window]
decorations         = "Buttonless"
padding             = { x = 0, y = 0 }
option_as_alt = "Both"

[mouse]
hide_when_typing    = false
