#!/bin/sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --add event aerospace_workspace_change

sketchybar --bar \
    corner_radius=10 \
    height=50 \
    blur_radius=20 \
    sticky=on \
    font_smoothing=on \
    color=0xff232136

sketchybar --default \
    label.font="ComicShannsMono Nerd Font:Bold:18" \
    label.color=0xffcdd6f4 \
    label.padding_left=5 \
    label.padding_right=5 \
    icon.drawing=off \
    background.padding_left=2 \
    background.padding_right=2 \
    background.color=0x00000000 \
    background.border_color=0xff6c7086 \
    background.border_width=2 \
    updates=on

sketchybar --add item battery right \
    --set battery update_freq=1 script="$PLUGIN_DIR/battery.sh" \
    icon.font="ComicShannsMono Nerd Font:Bold:18" \
    label.font="ComicShannsMono Nerd Font:Bold:18" \
    background.height=40 \
    background.color=0x00000000 \
    icon.padding_left=10 \
    icon.padding_right=5 \
    label.padding_right=10 \
    icon.drawing=on \
    icon.color=0xff908caa \
    label.color=0xff908caa \
    background.corner_radius=5

sketchybar --add item clock right \
    --set clock update_freq=1 icon=  script="$PLUGIN_DIR/testplug" \
    icon.font="ComicShannsMono Nerd Font:Bold:18" \
    label.font="ComicShannsMono Nerd Font:Bold:18" \
    background.height=40 \
    background.color=0x00000000 \
    icon.padding_left=10 \
    icon.padding_right=5 \
    label.padding_right=10 \
    icon.color=0xff908caa \
    label.color=0xff908caa \
    icon.drawing=on \
    background.corner_radius=5

sketchybar \
    --add item sound right \
    --set sound \
    background.height=40 \
    background.corner_radius=5 \
    icon.color=0xff908caa \
    label.color=0xff908caa \
    icon.padding_left=10 \
    icon.padding_right=5 \
    label=0 \
    icon="󰕿"\
    icon.font="ComicShannsMono Nerd Font:Bold:18" \
    label.padding_right=10 \
    icon.drawing=on \
    script="$PLUGIN_DIR/volume.sh" \
    --subscribe sound volume_change

for sid in {1..9} 
do
    sketchybar --add item space.$sid left \
        --set space.$sid update_freq=1 script="$PLUGIN_DIR/aerospace.sh" \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        label="$sid" \
        label.padding_left=10 \
        label.padding_right=10 \
        background.height=40 \
        background.corner_radius=5 \
        background.drawing=on \
        icon.drawing=on \
        icon.padding_left=10 \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/aerospace.sh $sid"
    done

    sketchybar --add item username center \
        --set username update_freq=1 icon=  script="$PLUGIN_DIR/resolution.sh" \
        icon.font="ComicShannsMono Nerd Font:Bold:18" \
        label.font="ComicShannsMono Nerd Font:Bold:18" \
        background.height=40 \
        background.color=0x00000000 \
        label.padding_left=10 \
        label.padding_right=10 \
        icon.color=0xff908caa \
        label.color=0xff908caa \
        icon.drawing=on \
        background.corner_radius=5
