enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

after-startup-command = [
    'exec-and-forget borders active_color=0xffc4a7e7 inactive_color=0x20494d64 width=5.0',
    'exec-and-forget sketchybar',
    'exec-and-forget open /Applications/Hammerspoon.app'
]

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

default-root-container-layout = 'tiles'
on-focused-monitor-changed    = ['move-mouse monitor-lazy-center']
on-focus-changed              = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 30
inner.vertical   = 30
outer.left       = 30
outer.bottom     = 30
outer.right      = 30
outer.top        = [{ monitor."Dell" = 60 }, 30]

[mode.main.binding]
cmd-h = []
