# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 didn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

after-startup-command = [
    'exec-and-forget borders active_color=0xffc4a7e7 inactive_color=0x20494d64 width=5.0',
    'exec-and-forget sketchybar',
    'exec-and-forget open /Applications/Hammerspoon.app'
]

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

default-root-container-layout = 'tiles'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.right =      5
outer.top =        5

[mode.main.binding]
cmd-h = []

[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run= [
  "layout floating",
]

